name: Node.js CI

on:
  push:
     tags:
       - '*'
  workflow_dispatch:

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all

    strategy:
      matrix:
        include:
#          - os: ubuntu-latest
#            artifact_name: mything
#            asset_name: Battle.net API Browser - linux-amd64
          - os: windows-latest

         

    steps:
    - uses: actions/checkout@v4
    - name: Build    
      run: npm run github-make-release
      working-directory: battlenet-api-browser
    - name: Upload web zip to release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/zip/web/*.zip"
        asset_name: Battlenet API Browser (Web) ${{ github.ref }}
        tag: ${{ github.ref }}
        prerelease: true
        allowUpdates: true
    - name: Upload windows setup.exe to release
      if: runner.os == 'Windows'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/squirrel.windows/x64/*.exe"
        asset_name: Battlenet API Browser (Windows x64) ${{ github.ref }}
        tag: ${{ github.ref }}
        prerelease: true
        allowUpdates: true        

    