name: Node.js CI

on:
  push:
     tags:
       - '*'
  workflow_dispatch:

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions: write-all

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-13
          - os: macos-latest

         

    steps:
    - uses: actions/checkout@v4
    - name: Build    
      run: npm run github-make-release-${{matrix.os}}
      working-directory: battlenet-api-browser
    - name: Get version from package.json
      id: get-version
      uses: beaconbrigade/package-json-version@v0.3.2
      with:
        path: battlenet-api-browser     
    - name: Upload web zip to release
      if: runner.os == 'Windows'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/zip/web/*.zip"
        name: Battlenet API Browser (Web) ${{ steps.get-version.outputs.version }}
        body: Version for hosting on a webserver.  Check CHANGELOG for changes
        prerelease: true
        allowUpdates: true
    - name: Upload windows setup.exe and .zip to release
      if: runner.os == 'Windows'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/squirrel.windows/x64/*.exe,battlenet-api-browser/out/make/zip/win32/x64/*.zip"
        name: Battlenet API Browser (Windows x64) ${{ steps.get-version.outputs.version }}
        body: Standalone Electron versions for Windows x64
        prerelease: true
        allowUpdates: true 
    - name: Upload linux .deb, .rpm, and .zip to release
      if: runner.os == 'Linux'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/zip/linux/*.zip, battlenet-api-browser/out/make/deb/x64/*.deb, battlenet-api-browser/out/make/rpm/x64/*.rpm"
        name: Battlenet API Browser (Linux x64) ${{ steps.get-version.outputs.version }}
        body: Standalone Electron versions for Linux
        prerelease: true
        allowUpdates: true        
    - name: Upload osx-m1 .zip to release
      if: matrix.os == 'macos-latest'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "battlenet-api-browser/out/make/zip/darwin/*.zip"
        name: Battlenet API Browser (OSX) ${{ steps.get-version.outputs.version }}
        body: Standalone Electron versions for OSX (M1)
        prerelease: true
        allowUpdates: true 
    - name: Upload osx-intel .zip to release
      if: matrix.os == 'macos-13'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "-api-browser/out/make/zip/darwin/*.zip"
        name: Battlenet API Browser (OSX) ${{ steps.get-version.outputs.version }}
        body: Standalone Electron versions for OSX (Intel)
        prerelease: true
        allowUpdates: true 
