name: Node.js CI

on:
  push:
     tags:
       - '*'
  workflow_dispatch:

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
#          - os: ubuntu-latest
#            artifact_name: mything
#            asset_name: Battle.net API Browser - linux-amd64
          - os: windows-latest
            artifact_name: "battlenet-api-browser-0.3.0-dev Setup.exe"
            asset_name: Battle.net API Browser - Windows x64
         

    steps:
    - uses: actions/checkout@v4
    - name: Build    
      run: npm run github-make-release
      working-directory: battlenet-api-browser
    - name: Upload web binary to release
      uses: svenstaro/upload-release-action@v2     
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: battlenet-api-browser/out/make/zip/web/battlenet-api-browser_*
        asset_name: Battlenet API Browser (Web)
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
    